---
# Prometheus Stack Deployment
# Core observability components for multi-tenant EKS

# Namespace for observability stack
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability

---
# ConfigMap for Prometheus AlertManager configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      slack_api_url: '{{ SLACK_WEBHOOK_URL }}'
    
    route:
      group_by: ['alertname', 'cluster', 'namespace', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'default'
      routes:
      - match:
          severity: critical
        receiver: 'critical'
        continue: true
        group_wait: 10s
        group_interval: 1m
      - match:
          severity: warning
        receiver: 'warning'
      - match:
          tenant: alpha
        receiver: 'tenant-alpha'
      - match:
          tenant: beta
        receiver: 'tenant-beta'
    
    receivers:
    - name: 'default'
      slack_configs:
      - channel: '#alerts'
        title: '{{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    
    - name: 'critical'
      slack_configs:
      - channel: '#critical-alerts'
        title: 'CRITICAL: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    
    - name: 'warning'
      slack_configs:
      - channel: '#warnings'
        title: 'WARNING: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    
    - name: 'tenant-alpha'
      slack_configs:
      - channel: '#tenant-alpha-alerts'
        title: 'Alpha Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    
    - name: 'tenant-beta'
      slack_configs:
      - channel: '#tenant-beta-alerts'
        title: 'Beta Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

---
# ConfigMap for Grafana dashboards - Tenant metrics
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-tenant-dashboard
  namespace: observability
  labels:
    grafana_dashboard: "1"
data:
  tenant-overview.json: |
    {
      "dashboard": {
        "id": null,
        "uid": "tenant-overview",
        "title": "Multi-Tenant Overview",
        "tags": ["multi-tenant", "overview"],
        "timezone": "browser",
        "schemaVersion": 30,
        "panels": [
          {
            "id": 1,
            "title": "Tenant Resource Usage",
            "targets": [
              {
                "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (namespace)"
              }
            ]
          },
          {
            "id": 2,
            "title": "Pod Count by Tenant",
            "targets": [
              {
                "expr": "count(kube_pod_info) by (namespace)"
              }
            ]
          },
          {
            "id": 3,
            "title": "Memory Usage by Tenant",
            "targets": [
              {
                "expr": "sum(container_memory_usage_bytes) by (namespace)"
              }
            ]
          },
          {
            "id": 4,
            "title": "ResourceQuota Status",
            "targets": [
              {
                "expr": "kube_resourcequota_used / kube_resourcequota_hard"
              }
            ]
          }
        ]
      }
    }

---
# Secret for external integrations
apiVersion: v1
kind: Secret
metadata:
  name: observability-external-services
  namespace: observability
type: Opaque
stringData:
  grafana-admin-password: "changeme" # Change in production
  slack-webhook-url: "" # Add your Slack webhook
  datadog-api-key: "" # Optional: DataDog integration
  newrelic-api-key: "" # Optional: New Relic integration

---
# ConfigMap for Prometheus custom scrape configs
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-scrape-configs
  namespace: observability
data:
  additional-scrape-configs.yaml: |
    # AWS CloudWatch integration (requires cloudwatch-exporter)
    - job_name: 'cloudwatch'
      scrape_interval: 5m
      metrics_path: '/probe'
      static_configs:
      - targets:
        - 'http://cloudwatch-exporter:9106'
    
    # EKS control plane metrics (if exposed)
    - job_name: 'eks-control-plane'
      scrape_interval: 30s
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod

---
# RBAC for observability namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-admin
  namespace: observability

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability-monitor
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - events
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - daemonsets
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]
- nonResourceURLs:
  - /metrics
  - /metrics/cadvisor
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: observability-monitor
subjects:
- kind: ServiceAccount
  name: observability-admin
  namespace: observability
