#!/bin/bash

# Quick reference for common CDK commands

echo "================================"
echo "AWS EKS CDK Quick Reference"
echo "================================"
echo ""

echo "📋 COMMON COMMANDS:"
echo ""
echo "1. Generate Templates (all environments)"
echo "   ./scripts/generate-templates.sh"
echo ""
echo "2. Build TypeScript"
echo "   npm run build"
echo ""
echo "3. Synthesize a specific environment"
echo "   npx cdk synth -c environment=dev"
echo "   npx cdk synth -c environment=staging"
echo "   npx cdk synth -c environment=prod"
echo ""
echo "4. Deploy infrastructure"
echo "   npx cdk deploy --all -c environment=dev"
echo "   npx cdk deploy --all -c environment=staging"
echo "   npx cdk deploy --all -c environment=prod --require-approval always"
echo ""
echo "5. Destroy infrastructure"
echo "   npx cdk destroy --all -c environment=dev"
echo "   npx cdk destroy --all -c environment=staging"
echo ""
echo "6. List stacks"
echo "   npx cdk list"
echo ""
echo "7. View differences (dry-run)"
echo "   npx cdk diff -c environment=dev"
echo ""
echo "8. Acknowledge CDK notices"
echo "   cdk acknowledge 32775 34892"
echo ""
echo "================================"
echo "📁 TEMPLATE LOCATIONS:"
echo ""
echo "   cdk.out/EksShowcase-{env}-Network.template.json"
echo "   cdk.out/EksShowcase-{env}-EKS.template.json"
echo "   cdk.out/EksShowcase-{env}-Storage.template.json"
echo "   cdk.out/EksShowcase-{env}-GitOps.template.json"
echo ""
echo "================================"
echo "🔐 AWS SETUP:"
echo ""
echo "   See AWS_SETUP.md for complete account configuration guide"
echo ""
echo "================================"
