#!/bin/bash

# Quick reference for common CDK commands

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         AWS EKS CDK & ArgoCD - Quick Reference                  ║"
echo "║                  (Project Root Directory)                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 COMMON COMMANDS (from project root):"
echo ""
echo "1. Generate Templates (all environments)"
echo "   ./scripts/generate-templates.sh"
echo ""
echo "2. Build TypeScript"
echo "   npm run build"
echo ""
echo "3. Synthesize templates for specific environment"
echo "   npm run synth          # dev (default)"
echo "   npm run synth:staging  # staging"
echo "   npm run synth:prod     # production"
echo ""
echo "4. Deploy infrastructure"
echo "   npm run deploy         # deploy to dev"
echo "   npm run deploy:prod    # deploy to prod with approval"
echo ""
echo "5. Destroy infrastructure"
echo "   npm run destroy        # destroy dev"
echo "   npm run destroy:prod   # destroy prod"
echo ""
echo "6. View differences (dry-run)"
echo "   cd iac && npx cdk diff -c environment=dev"
echo ""
echo "7. List all stacks"
echo "   cd iac && npx cdk list"
echo ""
echo "8. Acknowledge CDK notices"
echo "   cdk acknowledge 32775 34892"
echo ""
echo "════════════════════════════════════════════════════════════════="
echo "📁 TEMPLATE LOCATIONS:"
echo ""
echo "   iac/cdk.out/EksShowcase-{env}-Network.template.json"
echo "   iac/cdk.out/EksShowcase-{env}-EKS.template.json"
echo "   iac/cdk.out/EksShowcase-{env}-Storage.template.json"
echo "   iac/cdk.out/EksShowcase-{env}-GitOps.template.json"
echo ""
echo "════════════════════════════════════════════════════════════════="
echo "📚 DOCUMENTATION:"
echo ""
echo "   README.md                  - Main project documentation"
echo "   AWS_SETUP.md               - AWS account & credential setup"
echo "   docs/DEPLOYMENT_CHECKLIST  - Step-by-step deployment guide"
echo "   docs/QUICK_REFERENCE.md    - Extended command reference"
echo "   docs/START_HERE.md         - Navigation hub for all docs"
echo ""
echo "════════════════════════════════════════════════════════════════="
echo "🏗️  PROJECT STRUCTURE:"
echo ""
echo "   iac/                  - AWS Infrastructure (CDK) code"
echo "   platform/             - Kubernetes configuration manifests"
echo "   helm-charts/          - Reusable Helm charts"
echo "   docs/                 - Comprehensive documentation"
echo "   scripts/              - Helper scripts (this directory)"
echo ""
echo "════════════════════════════════════════════════════════════════"
