---
# Pod Security Standards - Restricted Policy
# Reference: https://kubernetes.io/docs/concepts/security/pod-security-standards/
# Apply to tenant namespaces for security hardening

# Policy for tenant-alpha - RESTRICTED (Production)
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted-alpha
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  allowedCapabilities: []
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'MustRunAs'
    seLinuxOptions:
      level: "s0:c123,c456"
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    - min: 1000
      max: 65535
  readOnlyRootFilesystem: false

---
# Pod Security Policy for beta - BASELINE (less restrictive)
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: baseline-beta
spec:
  privileged: false
  allowPrivilegeEscalation: true
  requiredDropCapabilities:
  - NET_RAW
  volumes:
  - '*'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'

---
# RBAC binding for restricted-alpha PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restricted-alpha-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - restricted-alpha

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restricted-alpha-psp
roleRef:
  kind: ClusterRole
  name: restricted-alpha-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
# Serviceaccounts in tenant-alpha namespace
- kind: Group
  name: system:serviceaccounts:tenant-alpha
  apiGroup: rbac.authorization.k8s.io

---
# RBAC binding for baseline-beta PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baseline-beta-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - baseline-beta

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: baseline-beta-psp
roleRef:
  kind: ClusterRole
  name: baseline-beta-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:tenant-beta
  apiGroup: rbac.authorization.k8s.io

---
# Pod Disruption Budget for observability components
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus-pdb
  namespace: observability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: prometheus

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana-pdb
  namespace: observability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: grafana

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alertmanager-pdb
  namespace: observability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: alertmanager

---
# Network Policies - Isolate kube-system namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kube-system-isolation
  namespace: kube-system
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow from same namespace
  - from:
    - podSelector: {}
  # Allow from nodes (kubelet)
  - from:
    - namespaceSelector: {}
  egress:
  # Allow all (system components need this)
  - to:
    - namespaceSelector: {}

---
# Security Context for tenant pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-security-context-defaults
  namespace: tenant-alpha
data:
  recommended-security-context.yaml: |
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
      fsGroupChangePolicy: "OnRootMismatch"
      seccompProfile:
        type: RuntimeDefault
    containers:
    - name: app
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop:
          - ALL

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-security-context-defaults
  namespace: tenant-beta
data:
  recommended-security-context.yaml: |
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
    containers:
    - name: app
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
